services:
  docs:
    image: alerts_protec_local_docs
    container_name: alerts_protec_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./alerts_protec:/app/alerts_protec:z
    ports:
      - '9000:9000'
    command: /start-docs
